
import mongoose from "mongoose";

const EventSchema = new mongoose.Schema({
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    auto: true
  },
  name: String,
  description: String,
  location: {
    lat: Number,
    lng: Number
  },
  pricePerPerson: Number,
  duration: Number,
  
  // Availability fields
  minPeople: Number,
  maxPeople: Number,
  availableTimeStart: Number,
  availableTimeEnd: Number,

  // Venue amenities
  address: String,
  district_url: String,
  wifi: Boolean,
  washroom: Boolean,
  banner_url: String,
  wheelchair: Boolean,

  // Event specific fields
  type: [{
    type: String,
    enum: [
      "Acoustic",
      "Art & Craft Workshops",
      "Attractions",
      "Beverage Tastings",
      "Bollywood Films",
      "Bollywood Music",
      "Bollywood Night",
      "Brunch",
      "Buffet",
      "Business Conferences & Talks",
      "Carnivals",
      "Celebrations",
      "Classical Music",
      "Clubbing",
      "Cocktails",
      "Comedy",
      "Comedy Open Mics",
      "Comical Plays",
      "Community Dining",
      "Community Meetups",
      "Concerts",
      "Conferences & Talks",
      "Cricket Matches",
      "Cricket Screenings",
      "DJ Nights",
      "Dance",
      "Dating",
      "Devotional Music",
      "Dinner",
      "Dramatic Plays",
      "EDM Music",
      "Education Conferences & Talks",
      "Entertainment & Award Shows",
      "Expos",
      "Fandom Fests",
      "Fests & Fairs",
      "Fitness & Wellness Fests",
      "Fitness Events",
      "Folk Music",
      "Food & Drinks",
      "Football Screenings",
      "Game Zones",
      "Gourmet Experiences",
      "Hip Hop Music",
      "Holi",
      "ICC",
      "Iconic Landmarks",
      "Indian Classical Dance",
      "Indie Music",
      "Industry Networking",
      "Instrumental Music",
      "Interest Based Communities",
      "Interest Based Dating",
      "Jams",
      "Jazz Music",
      "Karaoke Nights",
      "Kids",
      "Kids Festivals",
      "Kids Play",
      "Literary",
      "Literary Open Mics",
      "Live Gigs",
      "Lunch",
      "Marketing Conferences & Talks",
      "Motorsport Matches",
      "Movie Screenings",
      "Music",
      "Music Conferences & Talks",
      "Music Festivals",
      "Music Open Mics",
      "Nightlife",
      "ODI matches",
      "Open Air Screening",
      "Open Mics",
      "Open Mics & Jams",
      "Parties",
      "Performances",
      "Picnics",
      "Play",
      "Poetry",
      "Poetry Open Mics",
      "Pop Culture Fairs",
      "Pop Music",
      "Rave",
      "Roast",
      "Rock Music",
      "Singles Mixers",
      "Social Mixers",
      "Speed Dating",
      "Sports",
      "Standup",
      "Storytelling",
      "Storytelling Open Mics",
      "Sufi Music",
      "Sundowner",
      "TV Screenings",
      "Tech Conferences & Talks",
      "Techno",
      "Tennis Matches",
      "Theatre",
      "Trade Shows",
      "Tribute Shows",
      "Valentine's Day",
      "Workshops",
      "World Cup",
      "Wrestling Matches"
    ]
  }],
  venue: [{
    type: String,
    enum: ["indoor", "outdoor", "both"]
  }],

  parking: Boolean,
  rating: Number
}, {
  timestamps: true
});

export default mongoose.models.Event ||
  mongoose.model("Event", EventSchema);
